//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZyDMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormExchange
    {
        public int ID { get; set; }
        public int StuID { get; set; }
        public int OldDormID { get; set; }
        public int NewDormID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Dorm Dorm { get; set; }
        public virtual Dorm Dorm1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
