//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZyDMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dormitory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dormitory()
        {
            this.Dorm = new HashSet<Dorm>();
        }
    
        public int DormitoryID { get; set; }
        public string Name { get; set; }
        public int DormAdminID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dorm> Dorm { get; set; }
        public virtual DormAdmin DormAdmin { get; set; }
    }
}
