//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZyDMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AbsentRecord = new HashSet<AbsentRecord>();
            this.CheckIn = new HashSet<CheckIn>();
            this.DormExchange = new HashSet<DormExchange>();
            this.MoveOut = new HashSet<MoveOut>();
        }
    
        public int StuID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Account { get; set; }
        public string Pwd { get; set; }
        public string Photo { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> DormID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsentRecord> AbsentRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn> CheckIn { get; set; }
        public virtual Class Class { get; set; }
        public virtual Dorm Dorm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DormExchange> DormExchange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveOut> MoveOut { get; set; }
    }
}
