//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZyDMSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZyDMSystemEntities : DbContext
    {
        public ZyDMSystemEntities()
            : base("name=ZyDMSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsentRecord> AbsentRecord { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<CheckIn> CheckIn { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Dorm> Dorm { get; set; }
        public virtual DbSet<DormAdmin> DormAdmin { get; set; }
        public virtual DbSet<DormExchange> DormExchange { get; set; }
        public virtual DbSet<Dormitory> Dormitory { get; set; }
        public virtual DbSet<Major> Major { get; set; }
        public virtual DbSet<MoveOut> MoveOut { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
